# Generated by Django 2.1.4 on 2019-01-21 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPreIns',
            fields=[
                ('nombre', models.CharField(max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('valor', models.IntegerField()),
                ('clave_pri', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPreIns',
            fields=[
                ('nombre', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('numero_telefonico', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('numero_hijos', models.SmallIntegerField()),
                ('clave_pri', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
                ('plan_preferido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preinscripcion.PlanPreIns')),
            ],
        ),
    ]
